// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_login_user_api_token_post
 */
export type BodyLoginUserApiTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Gender
 */
export type Gender = 'male' | 'female' | 'other';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LabelRole
 */
export type LabelRole = 'admin' | 'agent';

/**
 * LabelStaffProfilePublic
 */
export type LabelStaffProfilePublic = {
    /**
     * Bio
     */
    bio: string | null;
    /**
     * Location
     */
    location: string | null;
    /**
     * Contact Email
     */
    contact_email: string | null;
    /**
     * Social Links
     */
    social_links: {
        [key: string]: unknown;
    } | null;
    /**
     * Position
     */
    position: string | null;
};

/**
 * LabelStaffProfileUpdate
 */
export type LabelStaffProfileUpdate = {
    /**
     * Bio
     */
    bio: string | null;
    /**
     * Location
     */
    location: string | null;
    /**
     * Contact Email
     */
    contact_email: string | null;
    /**
     * Social Links
     */
    social_links: {
        [key: string]: unknown;
    } | null;
    /**
     * Position
     */
    position: string | null;
};

/**
 * MembershipCreate
 */
export type MembershipCreate = {
    role: LabelRole;
};

/**
 * MembershipPublic
 */
export type MembershipPublic = {
    /**
     * Id
     */
    id: string;
    role: LabelRole;
};

/**
 * ProducerProfilePublic
 */
export type ProducerProfilePublic = {
    /**
     * Artist Name
     */
    artist_name: string | null;
    /**
     * Music Genre
     */
    music_genre: Array<string> | null;
    /**
     * Bio
     */
    bio: string | null;
    /**
     * Location
     */
    location: string | null;
    /**
     * Contact Email
     */
    contact_email: string | null;
    /**
     * Social Links
     */
    social_links: {
        [key: string]: unknown;
    } | null;
};

/**
 * ProducerProfileUpdate
 */
export type ProducerProfileUpdate = {
    /**
     * Artist Name
     */
    artist_name: string | null;
    /**
     * Music Genre
     */
    music_genre: Array<string> | null;
    /**
     * Bio
     */
    bio: string | null;
    /**
     * Location
     */
    location: string | null;
    /**
     * Contact Email
     */
    contact_email: string | null;
    /**
     * Social Links
     */
    social_links: {
        [key: string]: unknown;
    } | null;
};

/**
 * Status
 */
export type Status = 'PENDING' | 'WITHDRAWN' | 'IN_REVIEW' | 'SHORTLISTED' | 'ACCEPTED' | 'REJECTED';

/**
 * SubmissionCreate
 */
export type SubmissionCreate = {
    /**
     * Workspace Id
     */
    workspace_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Streaming Url
     */
    streaming_url: string;
    /**
     * Tempo
     */
    tempo: number;
    /**
     * Genre
     */
    genre?: Array<string> | null;
    /**
     * Key
     */
    key?: string | null;
    /**
     * Extra Metadata
     */
    extra_metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * SubmissionEventPublic
 */
export type SubmissionEventPublic = {
    /**
     * Id
     */
    id: string;
    status: Status;
    /**
     * Event Date
     */
    event_date: string;
    /**
     * Submission Id
     */
    submission_id: string;
    /**
     * Workspace Id
     */
    workspace_id: string;
    /**
     * Producer Profile Id
     */
    producer_profile_id: string | null;
    /**
     * Labelstaff Profile Id
     */
    labelstaff_profile_id: string | null;
};

/**
 * SubmissionPublic
 */
export type SubmissionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Producer Profile Id
     */
    producer_profile_id: string;
    /**
     * Workspace Id
     */
    workspace_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Streaming Url
     */
    streaming_url: string;
    /**
     * Tempo
     */
    tempo: number;
    /**
     * Genre
     */
    genre?: Array<string> | null;
    /**
     * Key
     */
    key?: string | null;
    /**
     * Extra Metadata
     */
    extra_metadata?: {
        [key: string]: unknown;
    } | null;
    status: Status;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * TrackCreate
 */
export type TrackCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Streaming Url
     */
    streaming_url: string;
    /**
     * Tempo
     */
    tempo: number;
    /**
     * Genre
     */
    genre: Array<string>;
    /**
     * Key
     */
    key?: string | null;
    /**
     * Extra Metadata
     */
    extra_metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * TrackPublic
 */
export type TrackPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Producer Profile Id
     */
    producer_profile_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Streaming Url
     */
    streaming_url: string;
    /**
     * Tempo
     */
    tempo: number;
    /**
     * Genre
     */
    genre: Array<string>;
    /**
     * Key
     */
    key?: string | null;
    /**
     * Extra Metadata
     */
    extra_metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * TrackUpdate
 */
export type TrackUpdate = {
    /**
     * Title
     */
    title: string | null;
    /**
     * Streaming Url
     */
    streaming_url: string | null;
    /**
     * Tempo
     */
    tempo: number | null;
    /**
     * Genre
     */
    genre: Array<string> | null;
    /**
     * Key
     */
    key: string | null;
    /**
     * Extra Metadata
     */
    extra_metadata: {
        [key: string]: unknown;
    } | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    gender?: Gender | null;
    user_type: UserType;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Created At
     */
    created_at: string;
    user_type: UserType;
};

/**
 * UserType
 */
export type UserType = 'producer' | 'labelstaff';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email: string | null;
    /**
     * Username
     */
    username: string | null;
    /**
     * Password
     */
    password: string | null;
    /**
     * First Name
     */
    first_name: string | null;
    /**
     * Last Name
     */
    last_name: string | null;
    gender: Gender | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WorkspaceCreate
 */
export type WorkspaceCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * WorkspacePublic
 */
export type WorkspacePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * WorkspaceUpdate
 */
export type WorkspaceUpdate = {
    /**
     * Name
     */
    name: string;
};

export type RegisterApiRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/register';
};

export type RegisterApiRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiRegisterPostError = RegisterApiRegisterPostErrors[keyof RegisterApiRegisterPostErrors];

export type RegisterApiRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserPublic;
};

export type RegisterApiRegisterPostResponse = RegisterApiRegisterPostResponses[keyof RegisterApiRegisterPostResponses];

export type LoginUserApiTokenPostData = {
    body: BodyLoginUserApiTokenPost;
    path?: never;
    query?: never;
    url: '/api/token';
};

export type LoginUserApiTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginUserApiTokenPostError = LoginUserApiTokenPostErrors[keyof LoginUserApiTokenPostErrors];

export type LoginUserApiTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginUserApiTokenPostResponse = LoginUserApiTokenPostResponses[keyof LoginUserApiTokenPostResponses];

export type ReadUserApiMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type ReadUserApiMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUserApiMeGetResponse = ReadUserApiMeGetResponses[keyof ReadUserApiMeGetResponses];

export type UpdateUserApiMePatchData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type UpdateUserApiMePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiMePatchError = UpdateUserApiMePatchErrors[keyof UpdateUserApiMePatchErrors];

export type UpdateUserApiMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserApiMePatchResponse = UpdateUserApiMePatchResponses[keyof UpdateUserApiMePatchResponses];

export type ReadProducerProfileApiUsersMeProducerProfileGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me/producer_profile';
};

export type ReadProducerProfileApiUsersMeProducerProfileGetResponses = {
    /**
     * Successful Response
     */
    200: ProducerProfilePublic;
};

export type ReadProducerProfileApiUsersMeProducerProfileGetResponse = ReadProducerProfileApiUsersMeProducerProfileGetResponses[keyof ReadProducerProfileApiUsersMeProducerProfileGetResponses];

export type UpdateProducerProfileApiUsersMeProducerProfilePatchData = {
    body: ProducerProfileUpdate;
    path?: never;
    query?: never;
    url: '/api/users/me/producer_profile';
};

export type UpdateProducerProfileApiUsersMeProducerProfilePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProducerProfileApiUsersMeProducerProfilePatchError = UpdateProducerProfileApiUsersMeProducerProfilePatchErrors[keyof UpdateProducerProfileApiUsersMeProducerProfilePatchErrors];

export type UpdateProducerProfileApiUsersMeProducerProfilePatchResponses = {
    /**
     * Successful Response
     */
    200: ProducerProfilePublic;
};

export type UpdateProducerProfileApiUsersMeProducerProfilePatchResponse = UpdateProducerProfileApiUsersMeProducerProfilePatchResponses[keyof UpdateProducerProfileApiUsersMeProducerProfilePatchResponses];

export type ReadLabelstaffProfileApiUsersMeLabelstaffProfileGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me/labelstaff_profile';
};

export type ReadLabelstaffProfileApiUsersMeLabelstaffProfileGetResponses = {
    /**
     * Successful Response
     */
    200: LabelStaffProfilePublic;
};

export type ReadLabelstaffProfileApiUsersMeLabelstaffProfileGetResponse = ReadLabelstaffProfileApiUsersMeLabelstaffProfileGetResponses[keyof ReadLabelstaffProfileApiUsersMeLabelstaffProfileGetResponses];

export type UpdateLabelstaffProfileApiUsersMeLabelstaffProfilePatchData = {
    body: LabelStaffProfileUpdate;
    path?: never;
    query?: never;
    url: '/api/users/me/labelstaff_profile';
};

export type UpdateLabelstaffProfileApiUsersMeLabelstaffProfilePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateLabelstaffProfileApiUsersMeLabelstaffProfilePatchError = UpdateLabelstaffProfileApiUsersMeLabelstaffProfilePatchErrors[keyof UpdateLabelstaffProfileApiUsersMeLabelstaffProfilePatchErrors];

export type UpdateLabelstaffProfileApiUsersMeLabelstaffProfilePatchResponses = {
    /**
     * Successful Response
     */
    200: LabelStaffProfilePublic;
};

export type UpdateLabelstaffProfileApiUsersMeLabelstaffProfilePatchResponse = UpdateLabelstaffProfileApiUsersMeLabelstaffProfilePatchResponses[keyof UpdateLabelstaffProfileApiUsersMeLabelstaffProfilePatchResponses];

export type ListTracksApiTracksGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tracks';
};

export type ListTracksApiTracksGetResponses = {
    /**
     * Response List Tracks Api Tracks Get
     *
     * Successful Response
     */
    200: Array<TrackPublic>;
};

export type ListTracksApiTracksGetResponse = ListTracksApiTracksGetResponses[keyof ListTracksApiTracksGetResponses];

export type AddTrackApiTracksPostData = {
    body: TrackCreate;
    path?: never;
    query?: never;
    url: '/api/tracks';
};

export type AddTrackApiTracksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddTrackApiTracksPostError = AddTrackApiTracksPostErrors[keyof AddTrackApiTracksPostErrors];

export type AddTrackApiTracksPostResponses = {
    /**
     * Successful Response
     */
    201: TrackPublic;
};

export type AddTrackApiTracksPostResponse = AddTrackApiTracksPostResponses[keyof AddTrackApiTracksPostResponses];

export type DeleteTrackApiTracksTrackIdDeleteData = {
    body?: never;
    path: {
        /**
         * Track Id
         */
        track_id: string;
    };
    query?: never;
    url: '/api/tracks/{track_id}';
};

export type DeleteTrackApiTracksTrackIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTrackApiTracksTrackIdDeleteError = DeleteTrackApiTracksTrackIdDeleteErrors[keyof DeleteTrackApiTracksTrackIdDeleteErrors];

export type DeleteTrackApiTracksTrackIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTrackApiTracksTrackIdDeleteResponse = DeleteTrackApiTracksTrackIdDeleteResponses[keyof DeleteTrackApiTracksTrackIdDeleteResponses];

export type EditTrackApiTracksTrackIdPatchData = {
    body: TrackUpdate;
    path: {
        /**
         * Track Id
         */
        track_id: string;
    };
    query?: never;
    url: '/api/tracks/{track_id}';
};

export type EditTrackApiTracksTrackIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditTrackApiTracksTrackIdPatchError = EditTrackApiTracksTrackIdPatchErrors[keyof EditTrackApiTracksTrackIdPatchErrors];

export type EditTrackApiTracksTrackIdPatchResponses = {
    /**
     * Successful Response
     */
    200: TrackPublic;
};

export type EditTrackApiTracksTrackIdPatchResponse = EditTrackApiTracksTrackIdPatchResponses[keyof EditTrackApiTracksTrackIdPatchResponses];

export type ListWorkspacesApiWorkspacesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/workspaces';
};

export type ListWorkspacesApiWorkspacesGetResponses = {
    /**
     * Response List Workspaces Api Workspaces Get
     *
     * Successful Response
     */
    200: Array<WorkspacePublic>;
};

export type ListWorkspacesApiWorkspacesGetResponse = ListWorkspacesApiWorkspacesGetResponses[keyof ListWorkspacesApiWorkspacesGetResponses];

export type CreateWorkspaceApiWorkspacesPostData = {
    body: WorkspaceCreate;
    path?: never;
    query?: never;
    url: '/api/workspaces';
};

export type CreateWorkspaceApiWorkspacesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWorkspaceApiWorkspacesPostError = CreateWorkspaceApiWorkspacesPostErrors[keyof CreateWorkspaceApiWorkspacesPostErrors];

export type CreateWorkspaceApiWorkspacesPostResponses = {
    /**
     * Successful Response
     */
    201: WorkspacePublic;
};

export type CreateWorkspaceApiWorkspacesPostResponse = CreateWorkspaceApiWorkspacesPostResponses[keyof CreateWorkspaceApiWorkspacesPostResponses];

export type DeleteWorkspaceApiWorkspacesWorkspaceIdDeleteData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}';
};

export type DeleteWorkspaceApiWorkspacesWorkspaceIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWorkspaceApiWorkspacesWorkspaceIdDeleteError = DeleteWorkspaceApiWorkspacesWorkspaceIdDeleteErrors[keyof DeleteWorkspaceApiWorkspacesWorkspaceIdDeleteErrors];

export type DeleteWorkspaceApiWorkspacesWorkspaceIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteWorkspaceApiWorkspacesWorkspaceIdDeleteResponse = DeleteWorkspaceApiWorkspacesWorkspaceIdDeleteResponses[keyof DeleteWorkspaceApiWorkspacesWorkspaceIdDeleteResponses];

export type UpdateWorkspaceApiWorkspacesWorkspaceIdPatchData = {
    body: WorkspaceUpdate;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}';
};

export type UpdateWorkspaceApiWorkspacesWorkspaceIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateWorkspaceApiWorkspacesWorkspaceIdPatchError = UpdateWorkspaceApiWorkspacesWorkspaceIdPatchErrors[keyof UpdateWorkspaceApiWorkspacesWorkspaceIdPatchErrors];

export type UpdateWorkspaceApiWorkspacesWorkspaceIdPatchResponses = {
    /**
     * Successful Response
     */
    200: WorkspacePublic;
};

export type UpdateWorkspaceApiWorkspacesWorkspaceIdPatchResponse = UpdateWorkspaceApiWorkspacesWorkspaceIdPatchResponses[keyof UpdateWorkspaceApiWorkspacesWorkspaceIdPatchResponses];

export type DeleteMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdDeleteData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Labelstaff Profile Id
         */
        labelstaff_profile_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/memberships/{labelstaff_profile_id}';
};

export type DeleteMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdDeleteError = DeleteMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdDeleteErrors[keyof DeleteMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdDeleteErrors];

export type DeleteMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdDeleteResponse = DeleteMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdDeleteResponses[keyof DeleteMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdDeleteResponses];

export type AddMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdPostData = {
    body: MembershipCreate;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Labelstaff Profile Id
         */
        labelstaff_profile_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/memberships/{labelstaff_profile_id}';
};

export type AddMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdPostError = AddMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdPostErrors[keyof AddMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdPostErrors];

export type AddMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdPostResponses = {
    /**
     * Successful Response
     */
    201: MembershipPublic;
};

export type AddMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdPostResponse = AddMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdPostResponses[keyof AddMemberApiWorkspacesWorkspaceIdMembershipsLabelstaffProfileIdPostResponses];

export type ListProducerSubmissionsApiSubmissionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/submissions';
};

export type ListProducerSubmissionsApiSubmissionsGetResponses = {
    /**
     * Response List Producer Submissions Api Submissions Get
     *
     * Successful Response
     */
    200: Array<SubmissionPublic>;
};

export type ListProducerSubmissionsApiSubmissionsGetResponse = ListProducerSubmissionsApiSubmissionsGetResponses[keyof ListProducerSubmissionsApiSubmissionsGetResponses];

export type CreateSubmissionApiSubmissionsPostData = {
    body: SubmissionCreate;
    path?: never;
    query?: never;
    url: '/api/submissions';
};

export type CreateSubmissionApiSubmissionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSubmissionApiSubmissionsPostError = CreateSubmissionApiSubmissionsPostErrors[keyof CreateSubmissionApiSubmissionsPostErrors];

export type CreateSubmissionApiSubmissionsPostResponses = {
    /**
     * Successful Response
     */
    201: SubmissionPublic;
};

export type CreateSubmissionApiSubmissionsPostResponse = CreateSubmissionApiSubmissionsPostResponses[keyof CreateSubmissionApiSubmissionsPostResponses];

export type ListLabelSubmissionsApiWorkspacesWorkspaceIdSubmissionsGetData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/submissions';
};

export type ListLabelSubmissionsApiWorkspacesWorkspaceIdSubmissionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListLabelSubmissionsApiWorkspacesWorkspaceIdSubmissionsGetError = ListLabelSubmissionsApiWorkspacesWorkspaceIdSubmissionsGetErrors[keyof ListLabelSubmissionsApiWorkspacesWorkspaceIdSubmissionsGetErrors];

export type ListLabelSubmissionsApiWorkspacesWorkspaceIdSubmissionsGetResponses = {
    /**
     * Response List Label Submissions Api Workspaces  Workspace Id  Submissions Get
     *
     * Successful Response
     */
    200: Array<SubmissionPublic>;
};

export type ListLabelSubmissionsApiWorkspacesWorkspaceIdSubmissionsGetResponse = ListLabelSubmissionsApiWorkspacesWorkspaceIdSubmissionsGetResponses[keyof ListLabelSubmissionsApiWorkspacesWorkspaceIdSubmissionsGetResponses];

export type TransitionToWithdrawnApiSubmissionsSubmissionIdWithdrawPostData = {
    body?: never;
    path: {
        /**
         * Submission Id
         */
        submission_id: string;
    };
    query?: never;
    url: '/api/submissions/{submission_id}/withdraw';
};

export type TransitionToWithdrawnApiSubmissionsSubmissionIdWithdrawPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransitionToWithdrawnApiSubmissionsSubmissionIdWithdrawPostError = TransitionToWithdrawnApiSubmissionsSubmissionIdWithdrawPostErrors[keyof TransitionToWithdrawnApiSubmissionsSubmissionIdWithdrawPostErrors];

export type TransitionToWithdrawnApiSubmissionsSubmissionIdWithdrawPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type TransitionToWithdrawnApiSubmissionsSubmissionIdWithdrawPostResponse = TransitionToWithdrawnApiSubmissionsSubmissionIdWithdrawPostResponses[keyof TransitionToWithdrawnApiSubmissionsSubmissionIdWithdrawPostResponses];

export type TransitionToInReviewApiWorkspacesWorkspaceIdSubmissionsSubmissionIdStartReviewPostData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Submission Id
         */
        submission_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/submissions/{submission_id}/start-review';
};

export type TransitionToInReviewApiWorkspacesWorkspaceIdSubmissionsSubmissionIdStartReviewPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransitionToInReviewApiWorkspacesWorkspaceIdSubmissionsSubmissionIdStartReviewPostError = TransitionToInReviewApiWorkspacesWorkspaceIdSubmissionsSubmissionIdStartReviewPostErrors[keyof TransitionToInReviewApiWorkspacesWorkspaceIdSubmissionsSubmissionIdStartReviewPostErrors];

export type TransitionToInReviewApiWorkspacesWorkspaceIdSubmissionsSubmissionIdStartReviewPostResponses = {
    /**
     * Successful Response
     */
    200: SubmissionPublic;
};

export type TransitionToInReviewApiWorkspacesWorkspaceIdSubmissionsSubmissionIdStartReviewPostResponse = TransitionToInReviewApiWorkspacesWorkspaceIdSubmissionsSubmissionIdStartReviewPostResponses[keyof TransitionToInReviewApiWorkspacesWorkspaceIdSubmissionsSubmissionIdStartReviewPostResponses];

export type TransitionToShortlistedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdShortlistPostData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Submission Id
         */
        submission_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/submissions/{submission_id}/shortlist';
};

export type TransitionToShortlistedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdShortlistPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransitionToShortlistedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdShortlistPostError = TransitionToShortlistedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdShortlistPostErrors[keyof TransitionToShortlistedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdShortlistPostErrors];

export type TransitionToShortlistedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdShortlistPostResponses = {
    /**
     * Successful Response
     */
    200: SubmissionPublic;
};

export type TransitionToShortlistedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdShortlistPostResponse = TransitionToShortlistedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdShortlistPostResponses[keyof TransitionToShortlistedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdShortlistPostResponses];

export type TransitionToAcceptedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdAcceptPostData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Submission Id
         */
        submission_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/submissions/{submission_id}/accept';
};

export type TransitionToAcceptedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdAcceptPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransitionToAcceptedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdAcceptPostError = TransitionToAcceptedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdAcceptPostErrors[keyof TransitionToAcceptedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdAcceptPostErrors];

export type TransitionToAcceptedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdAcceptPostResponses = {
    /**
     * Successful Response
     */
    200: SubmissionPublic;
};

export type TransitionToAcceptedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdAcceptPostResponse = TransitionToAcceptedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdAcceptPostResponses[keyof TransitionToAcceptedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdAcceptPostResponses];

export type TransitionToRejectedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdRejectPostData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Submission Id
         */
        submission_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/submissions/{submission_id}/reject';
};

export type TransitionToRejectedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdRejectPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransitionToRejectedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdRejectPostError = TransitionToRejectedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdRejectPostErrors[keyof TransitionToRejectedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdRejectPostErrors];

export type TransitionToRejectedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdRejectPostResponses = {
    /**
     * Successful Response
     */
    200: SubmissionPublic;
};

export type TransitionToRejectedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdRejectPostResponse = TransitionToRejectedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdRejectPostResponses[keyof TransitionToRejectedApiWorkspacesWorkspaceIdSubmissionsSubmissionIdRejectPostResponses];

export type ListProducerSubmissionEventsApiSubmissionsEventsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/submissions/events';
};

export type ListProducerSubmissionEventsApiSubmissionsEventsGetResponses = {
    /**
     * Response List Producer Submission Events Api Submissions Events Get
     *
     * Successful Response
     */
    200: Array<SubmissionEventPublic>;
};

export type ListProducerSubmissionEventsApiSubmissionsEventsGetResponse = ListProducerSubmissionEventsApiSubmissionsEventsGetResponses[keyof ListProducerSubmissionEventsApiSubmissionsEventsGetResponses];

export type ListLabelSubmissionEventsApiWorkspacesWorkspaceIdSubmissionsEventsGetData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/submissions/events';
};

export type ListLabelSubmissionEventsApiWorkspacesWorkspaceIdSubmissionsEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListLabelSubmissionEventsApiWorkspacesWorkspaceIdSubmissionsEventsGetError = ListLabelSubmissionEventsApiWorkspacesWorkspaceIdSubmissionsEventsGetErrors[keyof ListLabelSubmissionEventsApiWorkspacesWorkspaceIdSubmissionsEventsGetErrors];

export type ListLabelSubmissionEventsApiWorkspacesWorkspaceIdSubmissionsEventsGetResponses = {
    /**
     * Response List Label Submission Events Api Workspaces  Workspace Id  Submissions Events Get
     *
     * Successful Response
     */
    200: Array<SubmissionEventPublic>;
};

export type ListLabelSubmissionEventsApiWorkspacesWorkspaceIdSubmissionsEventsGetResponse = ListLabelSubmissionEventsApiWorkspacesWorkspaceIdSubmissionsEventsGetResponses[keyof ListLabelSubmissionEventsApiWorkspacesWorkspaceIdSubmissionsEventsGetResponses];

export type RootApiGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/';
};

export type RootApiGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
